version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.9-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Web UI